version: '3.7'
services:
  irmin:
    build:
      context: .
    command: serve --directory=./var --port=9090 --verbosity=info
    profiles:
      - setup
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - SERVER_HOST=irmin
    profiles:
      - test